### ISSUE TITLE
NaN values in returned reward from the Environment

### ISSUE THREAD

**Issue by rohitkumara** [leggedrobotics/raisimGym#14]
I am getting NaN values from the environment of the quadcopter. Can you tell me scenarios in which this can happen (Eg: Quadcopter is going out of bounds, quadcopter is rotating too fast etc.)?

TIA

**Comment by jhwangbo** [comment]
It happens when the policy becomes extreme and the angular velocity reaches too high values. This can happen since the angular velocity integration cannot be guaranteed to conserve energy. You can set a termination condition to prevent this (e.g., terminate if angular velocity norm is > 20).

**Comment by rohitkumara** [comment]
Okay, I shall try putting in constraints to stop the episode in extreme cases. I was also looking at the RAI bitbucket repository, and it requires access to the raigraphics_opengl repository. Is it possible to get access to this repository?

Thank you for clarification.

**Comment by jhwangbo** [comment]
rai is not managed anymore. I found that raisimGym way of workflow saves a lot of time. So I'll keep raigraphics_opengl closed for now (I had a license issue with the mesh files there). You can still find my original implementation of a quadrotor task in rai.

**Comment by rohitkumara** [comment]
Okay, I shall look into the quadcopter implementation. 

I looked into the issue of the NaN values and turn out, the `position_` variable has NaN values (in either x, y or z). After a bit more experimentation, I found out that reducing the number of environments to 50 and the number of threads to 1, I managed to avoid getting NaN values entirely. 

Is this because the cumulative of 500 environments * 40 threads was too large value? Could you shed some light on this behavior?

Thank you so much for your help.
