### ISSUE TITLE
use example in docker  it error Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by yonchien** [leggedrobotics/raisimGym#16]
my computer is i7 -8650U , have no gpu. I have tried using docker .but when I run python3 scripts/anymal_blind_locomotion.py. it said Segmentation fault (core dumped). what i can do ?
![Screenshot from 2019-10-16 17-31-30](https://user-images.githubusercontent.com/37019390/66906814-e0b15c00-f03a-11e9-8e24-5b93b8575a5e.png)

**Comment by jhwangbo** [comment]
I only made the GPU version. You are welcome to contribute a CPU version ;)

**Comment by yonchien** [comment]
what the difference between the GPU and CPU. NOW I use the cpu ,but it said Segmentation fault.  if your code can not use in CPU version

**Comment by jhwangbo** [comment]
It uses nvidia-docker. If you normal docker, it will be fine. Check stable-baselines docker files

**Comment by yonchien** [comment]
where is stable-baselines docker files
