### ISSUE TITLE
The normal docker error Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by yonchien** [leggedrobotics/raisimGym#17]
I tried yesterday.but still error Segmentation fault (core dumped).
I used the normal docker because I have no GPU. but I tried all examples , it error Segmentation fault (core dumped) and I can not found what's wrong . it occur when I load the raisimOgre
![Screenshot from 2019-10-17 10-51-39](https://user-images.githubusercontent.com/37019390/66973976-266a3500-f0cc-11e9-81cb-610e5e663cc4.png)

**Comment by jhwangbo** [comment]
If you dont use nvidia docker, i am not sure if you can render. All functionalities related to rendering are from Nividia. We are working on a remote visualizer and, until its release, you should save your policy and make a visualizer separately

**Comment by yonchien** [comment]
I tried the example cartpole . It still have this question .  I used raisimOgre before. but it run correctly .
if the raisimOgre are not render from Nividia. But I use the raisimGym it has problem . the tensorflow I use the CPU version, is there any relevant place in the raisimGym the uses GPU acceleration?

**Comment by jhwangbo** [comment]
tensorflow is the only place it uses gpu. I am not sure where it can be a problem. For now, I am not supporting cpu docker since it's hard to imagine any use case. If you get it working please contribute by a pull request.
