### ISSUE TITLE
undefined symbol error when running "python3 scripts/anymal_blind_locomotion.py"

### ISSUE THREAD

**Issue by inkyusa** [leggedrobotics/raisimGym#2]
Thank you for great work.
I faced the following error when executing "python3 scripts/anymal_blind_locomotion.py" command as instructed from the readme.

```shell
Traceback (most recent call last):
  File "scripts/anymal_bind_locomotion.py", line 2, in <module>
    from raisim_gym.env.RaisimGymVecEnv import RaisimGymVecEnv as Environment
  File "/home/username/miniconda3/envs/conda_raiGym/lib/python3.7/site-packages/raisim_gym-0.0.0-py3.7-linux-x86_64.egg/raisim_gym/__init__.py", line 1, in <module>
    from _raisim_gym import *
ImportError: /home/username/workspace/raisim_env/lib/libraisimOgre.so: undefined symbol: _ZN6aiNode8FindNodeEPKc
```
I am using Ubuntu 16.04, g++ 8, gcc8, with conda python 3.7.3, tf 1.14.0 (CPU), cmake 3.13.4
It looks like some version issue on Ogre...

**Comment by jhwangbo** [comment]
This is a raisimOgre issue. I found that in ubuntu 16.04, raisimOgre is linked against the system assimp. I included the assimp source and modified its CMakeLists.txt such that it always links to the right version. It has to be tested further but I am closing this issue for now.
