### ISSUE TITLE
Why does the simulation screen go black after a number of updates?

### ISSUE THREAD

**Issue by haloted** [leggedrobotics/raisimGym#23]
Not sure why but the screen goes pitch black after some time of training. What could cause this? 
![BlackScreen](https://user-images.githubusercontent.com/54319562/67997445-47c04900-fca8-11e9-987c-342d973d0528.png)

**Comment by jhwangbo** [comment]
Hi Ted, did you check the state? This can happen if the quadrotor goes outside of the bound
