### ISSUE TITLE
obMean and obStd in examples

### ISSUE THREAD

**Issue by iskanderuse** [leggedrobotics/raisimGym#31]
Can I ask the question about values of obMean_ and  obStd_ in examples?  How are the values ​​for these variables selected in the examples?

**Comment by jhwangbo** [comment]
They roughly scale your raw observation to zero mean and standard deviation of 1. They are chosen by using my intuition. You can also automatically do this by a moving-window averaging (implemented in stable-baselines but not included in raisimgym).
