### ISSUE TITLE
Search path when running a runner

### ISSUE THREAD

**Issue by charles-blouin** [leggedrobotics/raisimGym#32]
I was able to compile raisimGym as in the documentation. However, when I run

`python3 scripts/anymal_blind_locomotion.py`

I obtain the error:
```
  File "scripts/anymal_blind_locomotion.py", line 3, in <module>
    from raisim_gym.env.env.ANYmal import __ANYMAL_RESOURCE_DIRECTORY__ as __RSCDIR__
  File "/home/cha_blouin/raisim_workspace/raisimGym/raisim_gym/env/env/ANYmal/__init__.py", line 2, in <module>
    from _raisim_gym import *
ModuleNotFoundError: No module named '_raisim_gym'
```

I had to add raisimGym to the Pythonpath. Is that the way the module is intended to be installed? Without adding the folder to the pythonpath, there is an import error immediately with the missing raisim_gym package.

Thank you,

**Comment by jhwangbo** [comment]
`python3 setup installl ...` command in the readme should install _raisim_gym to your python path.
