### ISSUE TITLE
Question about the observation in Environment and Model

### ISSUE THREAD

**Issue by WatsonZhou12** [leggedrobotics/raisimGym#41]
Hi,
I encountered a problem that the value of "obDouble_"(ground truth) in Environment.hpp does not match the value of "self.obs" in ppo2.py. The dimension of both is the same while the value is not. 

For example, when I visualize the positions of the robot using the RewardLogger, the dynamic change of the value is ground truth (considering the robot shape and size). But when I try to print these positions using "print(self.obs)" in ppo2.py, the output does not match the ground truth. 

So what the self.obs represents? Why not equal to "obDouble_"(ground truth)? @jhwangbo 

Thanks!

**Comment by jhwangbo** [comment]
Obervation is scaled. You can also disable scaling in your environment by removing obMean and obStd

**Comment by WatsonZhou12** [comment]
Thanks!
