### ISSUE TITLE
turn off the visualization

### ISSUE THREAD

**Issue by ZQX323** [leggedrobotics/raisimGym#43]
Hello,

Thanks for your Repos. I have a question, I want to run raisimGym in a remote machine, so I can not visualize it in remote machine.  Errors is as follows:

[2020:06:08:12:50:32 OgreVis.hpp:342] Loading RaisimOgre Resources from: 
[2020:06:08:12:50:32 OgreVis.hpp:343] Loading OGRE Configurations from: /root/raisim_build/share/raisimOgre/cmake/../ogre/
Segmentation fault (core dumped)

Where can I find the config file to turn raisimOgre off such that there is no error?

**Comment by jhwangbo** [comment]
When you instantiate the environment, the constructor takes the location of the config file. For the anymal example, you can find it here: https://github.com/leggedrobotics/raisimGym/blob/master/raisim_gym/env/env/ANYmal/ANYmal_bear2/default_cfg.yaml

**Comment by ZQX323** [comment]
> When you instantiate the environment, the constructor takes the location of the config file. For the anymal example, you can find it here: https://github.com/leggedrobotics/raisimGym/blob/master/raisim_gym/env/env/ANYmal/ANYmal_bear2/default_cfg.yaml

It works, thanks for your help!

**Comment by ZQX323** [comment]
Hello Jemin,

Sorry to bother you again. It seems Anymal can only be controlled by 12 joint. Is there a function that can direct control the feet of Anymal? For example, direct move the endpoint of one leg from(0, 0, 0) to (1, 1, 0).
