### ISSUE TITLE
Struggling with LICENSE 

### ISSUE THREAD

**Issue by kashifzr** [leggedrobotics/raisimGym#49]
[2020:09:05:20:11:50 license.hpp:15] **THIS LICENSE IS EXPIRED. PLEASE GET A NEW LICENSE**

How to solve this LICENSE Problem. Does Its Free?

**Comment by jhwangbo** [comment]
you can pull raisimlib

**Comment by kashifzr** [comment]
Can You Explain! How to avoid this Problem.

**Comment by jhwangbo** [comment]
This was answered in #48. RaiSim Tech will distribute a free academic license for v1.0. Once it is ready, the instructions to get the license  will be posted in the raisimlib repo
