### ISSUE TITLE
wrong getGeneralizedForce()

### ISSUE THREAD

**Issue by floodsung** [leggedrobotics/raisimGym#5]
Hi, I tried to print getGeneralizedForce() but did not have a right force format.

**Comment by jhwangbo** [comment]
Hi floodsung, can you post this on raisimLib repo (https://github.com/leggedrobotics/raisimLib)? Just to keep it better organized. and Please provide more details there including the output and your system description. Thx

**Comment by jhwangbo** [comment]
It turns out that this was a bug in the example files. The joint position gain on one of the joints was set to zero. It is fixed in v0.3.2
